print("##############################")
print("#                            #")
print("#  Allano Lintang Ertantora  #")
print("#       2310817210004        #")
print("#                            #")
print("##############################")
