nama = input("Nama Lengkap: ").title()
nim = int(input("NIM: "))
klp = int(input("Kelas Paralel: "))
kota = input("Kota tempat lahir: ").title()
tgl = int(input("Tanggal lahir (dd): "))
bln = int(input("Bulan lahir (mm): "))
thn = int(input("Tahun lahir (yyyy): "))
almt = input("Alamat: ").title()
hob = input("Hobby: ")
no = input("No. HP: ")
print("Nama:", nama)
print("NIM:", nim)
print("Kelas Paralel:", klp)
print("Tempat/Tanggal Lahir:", kota +"/"+ str(tgl)+"-"+ str(bln)+"-"+str(thn))
print("Alamat:", almt)
print("Hobby:", hob)
print("No. HP:", no)